version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13.2
    restart: always
    environment:
      - TZ=Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "6100:6100"
    env_file:
      - ../.env
    command: -p 6100
