version: '3.3'

volumes:
  postgres_data:
  bot-data:

services:
  news_db:
    image: postgres:13.2
    restart: always
    container_name: latest_news_db
    environment:
      - TZ=Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "6100:6100"
    env_file:
      - ../.env
    command: -p 6100

  news_backend:
    image: abbadon666666/latest_news_bot:latest
    container_name: latest_news_bot
    restart: always
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - news_db
    volumes:
      - bot-data:/LATEST_NEWS_BOT/app/bot/
    ports:
      - "8080:8080"
    env_file:
      - ../.env

# Если на сервере не запущен nginx:
  # nginx:
  #   image: nginx:1.19.3
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend
