version: '3.3'

volumes:
  postgres_data:
  bot-data:

services:
  db:
    image: postgres:13.2
    restart: always
    container_name: latest_news_db
    environment:
      - TZ=Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "6100:6100"
    env_file:
      - ../.env
    command: -p 6100

  backend:
    image: abbadon666666/latest_news_bot:latest
    container_name: latest_news_bot
    restart: always
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - db
    volumes:
      - bot-data:/LATEST_NEWS_BOT/app/bot/
    ports:
      - "8000:8000"
    env_file:
      - ../.env