"""cascade option

Revision ID: 277a7f3ade68
Revises: 6547cda9ef8b
Create Date: 2023-03-13 20:06:55.861423

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '277a7f3ade68'
down_revision = '6547cda9ef8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
