"""autoincrement

Revision ID: 42ec8808acf7
Revises: da0f329dac4d
Create Date: 2023-03-26 23:44:33.806132

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '42ec8808acf7'
down_revision = 'da0f329dac4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
