"""video_link added

Revision ID: 44c042d1297b
Revises: 277a7f3ade68
Create Date: 2023-03-15 00:17:24.355626

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '44c042d1297b'
down_revision = '277a7f3ade68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('video_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'video_link')
    # ### end Alembic commands ###
