"""Optional chat_id

Revision ID: 4eab5418ff11
Revises: 04d5a25a9a5f
Create Date: 2023-04-17 01:26:54.640994

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4eab5418ff11'
down_revision = '04d5a25a9a5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
