"""video_preview added

Revision ID: 4eacd65ddb52
Revises: 4eab5418ff11
Create Date: 2023-05-13 21:45:27.815892

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4eacd65ddb52'
down_revision = '4eab5418ff11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('video_preview_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'video_preview_link')
    # ### end Alembic commands ###
