"""ondelete

Revision ID: 7c60f284cfcf
Revises: 44c042d1297b
Create Date: 2023-03-16 00:46:27.616610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c60f284cfcf'
down_revision = '44c042d1297b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_article_id_fkey', 'author', type_='foreignkey')
    op.create_foreign_key(None, 'author', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('infographic_article_id_fkey', 'infographic', type_='foreignkey')
    op.create_foreign_key(None, 'infographic', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'infographic', type_='foreignkey')
    op.create_foreign_key('infographic_article_id_fkey', 'infographic', 'article', ['article_id'], ['id'])
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.create_foreign_key('author_article_id_fkey', 'author', 'article', ['article_id'], ['id'])
    # ### end Alembic commands ###
