"""autoincrement

Revision ID: da0f329dac4d
Revises: 0112e416d455
Create Date: 2023-03-26 23:43:49.909166

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'da0f329dac4d'
down_revision = '0112e416d455'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articleuser',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'user_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articleuser')
    # ### end Alembic commands ###
